// Throw-away Thunderbird profile of the thunderbird-mcp lab. Copied into the profile on every run; the harness
// appends the scenario's own preferences. No network access is possible (--network none): these preferences
// mostly avoid attempts, delays and first-run windows.
// --- Accounts: Local Folders (server1) + a POP3 account on mailpit (server2), identity id1, SMTP smtp1 on mailpit.
user_pref("mail.accountmanager.accounts", "account2,account1");
user_pref("mail.accountmanager.defaultaccount", "account2");
user_pref("mail.accountmanager.localfoldersserver", "server1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.account.account2.identities", "id1");
user_pref("mail.server.server1.type", "none");
user_pref("mail.server.server1.hostname", "Local Folders");
user_pref("mail.server.server1.userName", "nobody");
user_pref("mail.server.server1.name", "Local Folders");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.type", "pop3");
user_pref("mail.server.server2.hostname", "127.0.0.1");
user_pref("mail.server.server2.port", 1110);
user_pref("mail.server.server2.userName", "lab");
user_pref("mail.server.server2.name", "Lab POP3 (mailpit)");
user_pref("mail.server.server2.socketType", 0);
user_pref("mail.server.server2.authMethod", 3);
user_pref("mail.server.server2.login_at_startup", false);
user_pref("mail.server.server2.check_new_mail", false);
user_pref("mail.server.server2.download_on_biff", false);
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.serverDefaultStoreContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.identity.id1.fullName", "Lab User");
user_pref("mail.identity.id1.useremail", "lab@example.test");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.compose_html", false);
user_pref("mail.identity.id1.draft_folder", "mailbox://nobody@Local%20Folders/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "1");
user_pref("mail.identity.id1.fcc", true);
user_pref("mail.identity.id1.fcc_folder", "mailbox://nobody@Local%20Folders/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "1");
user_pref("mail.identity.id1.stationery_folder", "mailbox://nobody@Local%20Folders/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "1");
user_pref("mail.identity.id1.archive_folder", "mailbox://nobody@Local%20Folders/Archives");
user_pref("mail.identity.id1.attach_signature", false);
user_pref("mail.identity.id1.reply_on_top", 0);
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "127.0.0.1");
user_pref("mail.smtpserver.smtp1.port", 1025);
user_pref("mail.smtpserver.smtp1.authMethod", 1);
user_pref("mail.smtpserver.smtp1.try_ssl", 0);
user_pref("mail.smtpserver.smtp1.username", "");
user_pref("mail.smtpserver.smtp1.description", "mailpit (lab)");
user_pref("mail.biff.show_alert", false);
user_pref("mail.biff.play_sound", false);
user_pref("mail.biff.show_tray_icon", false);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.check_all_imap_folders_for_new", false);

// --- First run, start pages, prompts.
user_pref("mail.provider.suppress_dialog_on_startup", true);
user_pref("mail.shell.checkDefaultClient", false);
user_pref("mailnews.start_page.enabled", false);
user_pref("mailnews.start_page.url", "about:blank");
user_pref("mailnews.start_page.override_url", "");
user_pref("mail.rights.version", 1);
user_pref("mail.inappnotifications.enabled", false);
user_pref("app.donation.eoy.version.viewed", 999);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("mail.winsearch.firstRunDone", true);
user_pref("mail.spotlight.firstRunDone", true);
user_pref("mail.openpgp.enable", false);
user_pref("mail.cloud_files.enabled", false);
user_pref("mail.tabs.firstTab.startupPage", "");
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("mailnews.database.global.indexer.enabled", false);
user_pref("calendar.integration.notify", false);
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("ui.systemUsesDarkTheme", 0);

// --- Updates, telemetry, remote services: all off.
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("app.update.disabledForTesting", true);
user_pref("app.update.checkInstallTime", false);
user_pref("app.update.staging.enabled", false);
user_pref("app.normandy.enabled", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.firstRunURL", "");
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.server", "data:,");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.crashreporter.enabled", false);
user_pref("browser.crashReports.unsubmittedCheck.enabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.systemAddon.update.enabled", false);
user_pref("extensions.blocklist.enabled", false);
user_pref("services.settings.server", "data:,");
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.provider.google4.updateURL", "");
user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);
user_pref("captivedetect.canonicalURL", "");
user_pref("network.dns.disablePrefetch", true);
user_pref("network.prefetch-next", false);
user_pref("network.predictor.enabled", false);
user_pref("network.manage-offline-status", false);
user_pref("offline.autoDetect", false);
user_pref("security.OCSP.enabled", 0);
user_pref("security.remote_settings.crlite_filters.enabled", false);
user_pref("security.remote_settings.intermediates.enabled", false);
user_pref("media.gmp-manager.url", "data:,");
user_pref("media.gmp-gmpopenh264.enabled", false);
user_pref("geo.enabled", false);
user_pref("browser.region.update.enabled", false);
user_pref("browser.region.network.url", "");
user_pref("browser.search.region", "US");
user_pref("mailnews.auto_config_url", "");
user_pref("mailnews.auto_config.fetchFromISP.enabled", false);
user_pref("mailnews.auto_config.guess.enabled", false);
user_pref("mailnews.mx_service_url", "");
user_pref("mail.instrumentation.postUrl", "");

// --- Extension under test: installed as <profile>/extensions/<id>.xpi, enabled without interaction, unsigned.
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.enabledScopes", 15);
user_pref("extensions.startupScanScopes", 1);
user_pref("xpinstall.signatures.required", false);
user_pref("extensions.experiments.enabled", true);
user_pref("extensions.installDistroAddons", false);

// --- Logging to Thunderbird's standard output (the harness log file).
user_pref("browser.dom.window.dump.enabled", true);
user_pref("devtools.console.stdout.chrome", true);
user_pref("devtools.console.stdout.content", true);
